name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Set up environment variables
      env:
        DATABASE_TESTING_URL: ${{ secrets.DATABASE_TESTING_URL }}
      run: |
        echo "DATABASE_TESTING_URL=$DATABASE_TESTING_URL" >> $GITHUB_ENV
        echo "DATABASE_TESTING_URL=$DATABASE_TESTING_URL"

    - run: npm ci

    # Uncomment this section if you need to run a build step
    # - run: npm run build --if-present

    - name: Run tests
      run: npm test